### ISSUE TITLE
Escape html characters found in Windows events with real-time eventlog component

### ISSUE THREAD

**Issue by willemdh** [mickem/nscp#154]
This week I experienced issues with some table overflow in the open service problems of my Nagios setup. Seems the issue was an event sent by the real-time eventlog component of 0.4.1.105. As we would prefer to allow html tags so links are recognized, I would think it would be an enhancement if characters found in Windows events were properly escaped?

An example real-time eventlog causing issues:

An event or events were not traced.
Original event string:

    <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Stop"><TraceIdentifier>http://msdn.microsoft.com/nl-BE/library/System.ServiceModel.Diagnostics.ActivityBoundary.aspx</TraceIdentifier><Description>Activity boundary.</Description><AppDomain>/LM/W3SVC/1622073421/Root/Digipolis/Digipolis.EPostService-1-130771764073324544</AppDomain><ExtendedData xmlns="http://schemas.microsoft.com/2006/08/ServiceModel/DictionaryTraceRecord"><ActivityName>Execute 'Digipolis.AlfrescoService.IDocumentService.GetChildren'.</ActivityName><ActivityType>ExecuteUserCode</ActivityType></ExtendedData></TraceRecord>
    Exception: System.IO.IOException: The drive cannot find the sector requested.
    
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
       at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
       at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
       at System.IO.StreamWriter.Write(String value)
       at System.Diagnostics.XmlWriterTraceListener.WriteEscaped(String str)
       at System.Diagnostics.XmlWriterTraceListener.WriteStartHeader(String source, TraceEventType eventType, Int32 id, TraceEventCache eventCache)
       at System.Diagnostics.XmlWriterTraceListener.TraceData(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, Object data)
       at System.Diagnostics.TraceSource.TraceData(TraceEventType eventType, Int32 id, Object data)
       at System.ServiceModel.Diagnostics.DiagnosticTrace.TraceEvent(TraceEventType type, Int32 code, String msdnTraceCode, String description, TraceRecord trace, Exception exception, Object source)
    Process Name: w3wp
    Process ID: 94168

The > and < should be escaped to prevent issues in Nagios?

EDIT: I just saw it seems GitHub does escape the characters, hence they are not visible... :)

Grtz

Willem

**Comment by mickem** [comment]
Hmm, not sure this makes sense really, or is there some standard for logging to eventlog as html?

Problem is that Nagios does not really support HTML (as the plugin guidelines dictate text right, or have I missed somthing?

**Comment by willemdh** [comment]
Nagios XI has a checkbox somewhere that can be enabled to support html to enable us to click links. I had to disable it to prevent this table overflow issue.

**Comment by mickem** [comment]
Ok, will see if I can add some "html" support... probably nothing I will add in the nearest future, so let me know if this is "urgent"...

**Comment by willemdh** [comment]
This is not urgent.
